#!/bin/bash
#PBS -N base_train_mix4u
#PBS -q normal
#PBS -P 11610002
#PBS -l select=1:ngpus=4
#PBS -l walltime=12:00:00

export PYTHONUNBUFFERED=1
export NANOCHAT_BASE_DIR=output

cd "$PBS_O_WORKDIR" || exit 1
source ~/miniconda3/etc/profile.d/conda.sh

exec > "pbs-${PBS_JOBID}.out" 2> "pbs-${PBS_JOBID}.err"

set -x
~/miniconda3/bin/torchrun --standalone --nproc_per_node=4 -m scripts.base_train_mix --save-every 2000 --continue-to-chat-sft --model-tag "$PBS_JOBID" $input